try(library(rlang))
try(library(conveniencefunctions))
try(library(forcats))
try(library(stringr))
try(library(dplyr))
try(library(purrr))
try(library(readr))
try(library(tidyr))
try(library(tibble))
try(library(ggplot2))
try(library(tidyverse))
try(library(stats))
try(library(graphics))
try(library(grDevices))
try(library(utils))
try(library(datasets))
try(library(methods))
try(library(base))
setwd('~/tmp_xcdq6_1_folder')
rm(list = ls())

load('tmp_xcdq6.RData')
files <- list.files(pattern = '.so')
for (f in files) dyn.load(f)
.node <- 1
.runbgOutput <- try(1:5)
save(.runbgOutput, file = 'tmp_xcdq6_1_result.RData')