try(library(rlang))
try(library(conveniencefunctions))
try(library(forcats))
try(library(stringr))
try(library(dplyr))
try(library(purrr))
try(library(readr))
try(library(tidyr))
try(library(tibble))
try(library(ggplot2))
try(library(tidyverse))
try(library(stats))
try(library(graphics))
try(library(grDevices))
try(library(utils))
try(library(datasets))
try(library(methods))
try(library(base))
setwd('~/tmp_2agnh_1_folder')
rm(list = ls())
cfiles <- list.files(pattern = '.c$')
cppfiles <- list.files(pattern = '.cpp$')
filelist <- paste(paste(cfiles, collapse = ' '), paste(cppfiles, collapse = ' '))
filename0 <- 'tmp_2agnh'
system(paste0('R CMD SHLIB ', filelist, ' -o ', filename0, '.so'))
load('tmp_2agnh.RData')
files <- list.files(pattern = '.so')
for (f in files) dyn.load(f)
.node <- 1
.runbgOutput <- try(1:5)
save(.runbgOutput, file = 'tmp_2agnh_1_result.RData')