/** Code auto-generated by cOde 0.4 **/
#include <R.h> 
 #include <math.h> 

static double parms[13];
static double forc[0];
static double cons[0];
static double eventcounter[1];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define k1 parms[0] 
 #define k2 parms[1] 
 #define A_add parms[2] 
 #define y0_0 parms[3] 
 #define y1_0 parms[4] 
 #define y2_0 parms[5] 
 #define y3_0 parms[6] 
 #define y4_0 parms[7] 
 #define y5_0 parms[8] 
 #define y6_0 parms[9] 
 #define y7_0 parms[10] 
 #define y8_0 parms[11] 
 #define y9_0 parms[12] 
#define tmin range[0]
#define tmax range[1]


void odemodel_a5196e58_s_initmod(void (* odeparms)(int *, double *)) {
	 int N=13;
	 odeparms(&N, parms);
	 for(int i=0; i<1; ++i) eventcounter[i] = 0;
}

void odemodel_a5196e58_s_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void odemodel_a5196e58_s_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -1.0*(k1*y[0]);
 	 ydot[1] = 1.0*(k1*y[0])-1.0*(k2*y[1]);
 	 ydot[2] = (-k1)*(y[2]);
 	 ydot[3] = (k1)*(y[2])+(-k2)*(y[3]);
 	 ydot[4] = (k1)*(0.0)+(-k2)*(y[4]);
 	 ydot[5] = (-k1)*(y[5])+-y[0];
 	 ydot[6] = (k1)*(y[5])+(-k2)*(y[6])+y[0];
 	 ydot[7] = (k1)*(0.0)+(-k2)*(y[7])+-y[1];
 	 ydot[8] = (-k1)*(y[8]);
 	 ydot[9] = (k1)*(y[8])+(-k2)*(y[9]);

	 for(int i=  0 ; i <  2 ; ++i) RPAR[i] = 0;
}

/** Event function **/
void odemodel_a5196e58_s_myevent(int *n, double *t, double *y) {

	 if(*t == 5.0 & eventcounter[0] == 0) {
		y[2] = y[2] + 0;
		y[5] = y[5] + 0;
		y[8] = y[8] + 1.0;
		y[0] = y[0] + A_add;
		eventcounter[0] = 1.;
	 }


}
