/** Code auto-generated by cOde 1.1.0 **/
#include <R.h> 
 #include <math.h> 

static double parms[17];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define cytoplasm parms[0] 
 #define y0_0 parms[1] 
 #define y1_0 parms[2] 
 #define y2_0 parms[3] 
 #define y3_0 parms[4] 
 #define y4_0 parms[5] 
 #define y5_0 parms[6] 
 #define y6_0 parms[7] 
 #define y7_0 parms[8] 
 #define y8_0 parms[9] 
 #define y9_0 parms[10] 
 #define y10_0 parms[11] 
 #define y11_0 parms[12] 
 #define y12_0 parms[13] 
 #define y13_0 parms[14] 
 #define y14_0 parms[15] 
 #define y15_0 parms[16] 
#define tmin range[0]
#define tmax range[1]


void odemodel_enzymeKinetics_s_initmod(void (* odeparms)(int *, double *)) {
	 int N=17;
	 odeparms(&N, parms);
}

void odemodel_enzymeKinetics_s_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void odemodel_enzymeKinetics_s_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -1.0*(y[0]*y[1]*cytoplasm)+1.0*(y[2]*cytoplasm)+1.0*(y[2]*cytoplasm);
 	 ydot[1] = -1.0*(y[0]*y[1]*cytoplasm)+1.0*(y[2]*cytoplasm);
 	 ydot[2] = 1.0*(y[0]*y[1]*cytoplasm)-1.0*(y[2]*cytoplasm)-1.0*(y[2]*cytoplasm);
 	 ydot[3] = 1.0*(y[2]*cytoplasm);
 	 ydot[4] = (-(y[1]*cytoplasm))*(y[4])+(-(y[0]*cytoplasm))*(y[5])+(cytoplasm+cytoplasm)*(y[6]);
 	 ydot[5] = (-(y[1]*cytoplasm))*(y[4])+(-(y[0]*cytoplasm))*(y[5])+(cytoplasm)*(y[6]);
 	 ydot[6] = (y[1]*cytoplasm)*(y[4])+(y[0]*cytoplasm)*(y[5])+(-(cytoplasm+cytoplasm))*(y[6]);
 	 ydot[7] = (cytoplasm)*(y[6]);
 	 ydot[8] = (-(y[1]*cytoplasm))*(y[8])+(-(y[0]*cytoplasm))*(y[9])+(cytoplasm+cytoplasm)*(y[10]);
 	 ydot[9] = (-(y[1]*cytoplasm))*(y[8])+(-(y[0]*cytoplasm))*(y[9])+(cytoplasm)*(y[10]);
 	 ydot[10] = (y[1]*cytoplasm)*(y[8])+(y[0]*cytoplasm)*(y[9])+(-(cytoplasm+cytoplasm))*(y[10]);
 	 ydot[11] = (cytoplasm)*(y[10]);
 	 ydot[12] = (-(y[1]*cytoplasm))*(y[12])+(-(y[0]*cytoplasm))*(y[13])+(cytoplasm+cytoplasm)*(y[14]);
 	 ydot[13] = (-(y[1]*cytoplasm))*(y[12])+(-(y[0]*cytoplasm))*(y[13])+(cytoplasm)*(y[14]);
 	 ydot[14] = (y[1]*cytoplasm)*(y[12])+(y[0]*cytoplasm)*(y[13])+(-(cytoplasm+cytoplasm))*(y[14]);
 	 ydot[15] = (cytoplasm)*(y[14]);

}

