/** Code auto-generated by cOde 1.1.0 **/
#include <R.h> 
 #include <math.h> 

static double parms[64];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 2 
#define nSplines 0 
#define precision 1e-05 

#define Epo_degradation_BaF3 parms[0] 
 #define k_phos parms[1] 
 #define k_exp_homo parms[2] 
 #define nuc parms[3] 
 #define cyt parms[4] 
 #define k_exp_hetero parms[5] 
 #define k_imp_homo parms[6] 
 #define k_imp_hetero parms[7] 
 #define y0_0 parms[8] 
 #define y1_0 parms[9] 
 #define y2_0 parms[10] 
 #define y3_0 parms[11] 
 #define y4_0 parms[12] 
 #define y5_0 parms[13] 
 #define y6_0 parms[14] 
 #define y7_0 parms[15] 
 #define y8_0 parms[16] 
 #define y9_0 parms[17] 
 #define y10_0 parms[18] 
 #define y11_0 parms[19] 
 #define y12_0 parms[20] 
 #define y13_0 parms[21] 
 #define y14_0 parms[22] 
 #define y15_0 parms[23] 
 #define y16_0 parms[24] 
 #define y17_0 parms[25] 
 #define y18_0 parms[26] 
 #define y19_0 parms[27] 
 #define y20_0 parms[28] 
 #define y21_0 parms[29] 
 #define y22_0 parms[30] 
 #define y23_0 parms[31] 
 #define y24_0 parms[32] 
 #define y25_0 parms[33] 
 #define y26_0 parms[34] 
 #define y27_0 parms[35] 
 #define y28_0 parms[36] 
 #define y29_0 parms[37] 
 #define y30_0 parms[38] 
 #define y31_0 parms[39] 
 #define y32_0 parms[40] 
 #define y33_0 parms[41] 
 #define y34_0 parms[42] 
 #define y35_0 parms[43] 
 #define y36_0 parms[44] 
 #define y37_0 parms[45] 
 #define y38_0 parms[46] 
 #define y39_0 parms[47] 
 #define y40_0 parms[48] 
 #define y41_0 parms[49] 
 #define y42_0 parms[50] 
 #define y43_0 parms[51] 
 #define y44_0 parms[52] 
 #define y45_0 parms[53] 
 #define y46_0 parms[54] 
 #define y47_0 parms[55] 
 #define y48_0 parms[56] 
 #define y49_0 parms[57] 
 #define y50_0 parms[58] 
 #define y51_0 parms[59] 
 #define y52_0 parms[60] 
 #define y53_0 parms[61] 
 #define y54_0 parms[62] 
 #define y55_0 parms[63] 
#define tmin range[0]
#define tmax range[1]


void odemodel_Boehm_JProteomeRes2014_s_initmod(void (* odeparms)(int *, double *)) {
	 int N=64;
	 odeparms(&N, parms);
}

void odemodel_Boehm_JProteomeRes2014_s_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void odemodel_Boehm_JProteomeRes2014_s_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(pow(y[0],2.00e+00))*k_phos)-1.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*y[2]*k_phos)+2.00e+00*(1.00e+00*k_exp_homo*y[5])*(nuc/cyt)+1.00e+00*(1.00e+00*k_exp_hetero*y[6])*(nuc/cyt);
 	 ydot[1] = 1.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(pow(y[0],2.00e+00))*k_phos)-1.00e+00*(1.00e+00*k_imp_homo*y[1]);
 	 ydot[2] = -1.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*y[2]*k_phos)-2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(pow(y[2],2.00e+00))*k_phos)+1.00e+00*(1.00e+00*k_exp_hetero*y[6])*(nuc/cyt)+2.00e+00*(1.00e+00*k_exp_homo*y[7])*(nuc/cyt);
 	 ydot[3] = 1.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*y[2]*k_phos)-1.00e+00*(1.00e+00*k_imp_hetero*y[3]);
 	 ydot[4] = 1.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(pow(y[2],2.00e+00))*k_phos)-1.00e+00*(1.00e+00*k_imp_homo*y[4]);
 	 ydot[5] = 1.00e+00*(1.00e+00*k_imp_homo*y[1])*(cyt/nuc)-1.00e+00*(1.00e+00*k_exp_homo*y[5]);
 	 ydot[6] = 1.00e+00*(1.00e+00*k_imp_hetero*y[3])*(cyt/nuc)-1.00e+00*(1.00e+00*k_exp_hetero*y[6]);
 	 ydot[7] = 1.00e+00*(1.00e+00*k_imp_homo*y[4])*(cyt/nuc)-1.00e+00*(1.00e+00*k_exp_homo*y[7]);
 	 ydot[8] = (-(2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[0])*k_phos)+1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos))*(y[8])+(-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos))*(y[10])+(2.00e+00*(1.00e+00*k_exp_homo)*(nuc/cyt))*(y[13])+(1.00e+00*k_exp_hetero*(nuc/cyt))*(y[14])+2.00e+00*(1.25e-07*(exp(-1.00e+00*Epo_degradation_BaF3*time)*time)*(pow(y[0],2.00e+00))*k_phos)+1.25e-07*(exp(-1.00e+00*Epo_degradation_BaF3*time)*time)*y[0]*y[2]*k_phos;
 	 ydot[9] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[0])*k_phos)*(y[8])+(-(1.00e+00*k_imp_homo))*(y[9])-(1.25e-07*(exp(-1.00e+00*Epo_degradation_BaF3*time)*time)*(pow(y[0],2.00e+00))*k_phos);
 	 ydot[10] = (-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos))*(y[8])+(-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos+2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[2])*k_phos)))*(y[10])+(1.00e+00*k_exp_hetero*(nuc/cyt))*(y[14])+(2.00e+00*(1.00e+00*k_exp_homo)*(nuc/cyt))*(y[15])+1.25e-07*(exp(-1.00e+00*Epo_degradation_BaF3*time)*time)*y[0]*y[2]*k_phos+2.00e+00*(1.25e-07*(exp(-1.00e+00*Epo_degradation_BaF3*time)*time)*(pow(y[2],2.00e+00))*k_phos);
 	 ydot[11] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos)*(y[8])+(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos)*(y[10])+(-(1.00e+00*k_imp_hetero))*(y[11])-(1.25e-07*(exp(-1.00e+00*Epo_degradation_BaF3*time)*time)*y[0]*y[2]*k_phos);
 	 ydot[12] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[2])*k_phos)*(y[10])+(-(1.00e+00*k_imp_homo))*(y[12])-(1.25e-07*(exp(-1.00e+00*Epo_degradation_BaF3*time)*time)*(pow(y[2],2.00e+00))*k_phos);
 	 ydot[13] = (1.00e+00*k_imp_homo*(cyt/nuc))*(y[9])+(-(1.00e+00*k_exp_homo))*(y[13]);
 	 ydot[14] = (1.00e+00*k_imp_hetero*(cyt/nuc))*(y[11])+(-(1.00e+00*k_exp_hetero))*(y[14]);
 	 ydot[15] = (1.00e+00*k_imp_homo*(cyt/nuc))*(y[12])+(-(1.00e+00*k_exp_homo))*(y[15]);
 	 ydot[16] = (-(2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[0])*k_phos)+1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos))*(y[16])+(-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos))*(y[18])+(2.00e+00*(1.00e+00*k_exp_homo)*(nuc/cyt))*(y[21])+(1.00e+00*k_exp_hetero*(nuc/cyt))*(y[22])-(2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(pow(y[0],2.00e+00)))+1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*y[2]);
 	 ydot[17] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[0])*k_phos)*(y[16])+(-(1.00e+00*k_imp_homo))*(y[17])+1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(pow(y[0],2.00e+00));
 	 ydot[18] = (-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos))*(y[16])+(-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos+2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[2])*k_phos)))*(y[18])+(1.00e+00*k_exp_hetero*(nuc/cyt))*(y[22])+(2.00e+00*(1.00e+00*k_exp_homo)*(nuc/cyt))*(y[23])-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*y[2]+2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(pow(y[2],2.00e+00))));
 	 ydot[19] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos)*(y[16])+(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos)*(y[18])+(-(1.00e+00*k_imp_hetero))*(y[19])+1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*y[2];
 	 ydot[20] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[2])*k_phos)*(y[18])+(-(1.00e+00*k_imp_homo))*(y[20])+1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(pow(y[2],2.00e+00));
 	 ydot[21] = (1.00e+00*k_imp_homo*(cyt/nuc))*(y[17])+(-(1.00e+00*k_exp_homo))*(y[21]);
 	 ydot[22] = (1.00e+00*k_imp_hetero*(cyt/nuc))*(y[19])+(-(1.00e+00*k_exp_hetero))*(y[22]);
 	 ydot[23] = (1.00e+00*k_imp_homo*(cyt/nuc))*(y[20])+(-(1.00e+00*k_exp_homo))*(y[23]);
 	 ydot[24] = (-(2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[0])*k_phos)+1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos))*(y[24])+(-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos))*(y[26])+(2.00e+00*(1.00e+00*k_exp_homo)*(nuc/cyt))*(y[29])+(1.00e+00*k_exp_hetero*(nuc/cyt))*(y[30])+2.00e+00*y[5]*(nuc/cyt);
 	 ydot[25] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[0])*k_phos)*(y[24])+(-(1.00e+00*k_imp_homo))*(y[25]);
 	 ydot[26] = (-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos))*(y[24])+(-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos+2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[2])*k_phos)))*(y[26])+(1.00e+00*k_exp_hetero*(nuc/cyt))*(y[30])+(2.00e+00*(1.00e+00*k_exp_homo)*(nuc/cyt))*(y[31])+2.00e+00*y[7]*(nuc/cyt);
 	 ydot[27] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos)*(y[24])+(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos)*(y[26])+(-(1.00e+00*k_imp_hetero))*(y[27]);
 	 ydot[28] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[2])*k_phos)*(y[26])+(-(1.00e+00*k_imp_homo))*(y[28]);
 	 ydot[29] = (1.00e+00*k_imp_homo*(cyt/nuc))*(y[25])+(-(1.00e+00*k_exp_homo))*(y[29])-y[5];
 	 ydot[30] = (1.00e+00*k_imp_hetero*(cyt/nuc))*(y[27])+(-(1.00e+00*k_exp_hetero))*(y[30]);
 	 ydot[31] = (1.00e+00*k_imp_homo*(cyt/nuc))*(y[28])+(-(1.00e+00*k_exp_homo))*(y[31])-y[7];
 	 ydot[32] = (-(2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[0])*k_phos)+1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos))*(y[32])+(-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos))*(y[34])+(2.00e+00*(1.00e+00*k_exp_homo)*(nuc/cyt))*(y[37])+(1.00e+00*k_exp_hetero*(nuc/cyt))*(y[38])+y[6]*(nuc/cyt);
 	 ydot[33] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[0])*k_phos)*(y[32])+(-(1.00e+00*k_imp_homo))*(y[33]);
 	 ydot[34] = (-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos))*(y[32])+(-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos+2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[2])*k_phos)))*(y[34])+(1.00e+00*k_exp_hetero*(nuc/cyt))*(y[38])+(2.00e+00*(1.00e+00*k_exp_homo)*(nuc/cyt))*(y[39])+y[6]*(nuc/cyt);
 	 ydot[35] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos)*(y[32])+(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos)*(y[34])+(-(1.00e+00*k_imp_hetero))*(y[35]);
 	 ydot[36] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[2])*k_phos)*(y[34])+(-(1.00e+00*k_imp_homo))*(y[36]);
 	 ydot[37] = (1.00e+00*k_imp_homo*(cyt/nuc))*(y[33])+(-(1.00e+00*k_exp_homo))*(y[37]);
 	 ydot[38] = (1.00e+00*k_imp_hetero*(cyt/nuc))*(y[35])+(-(1.00e+00*k_exp_hetero))*(y[38])-y[6];
 	 ydot[39] = (1.00e+00*k_imp_homo*(cyt/nuc))*(y[36])+(-(1.00e+00*k_exp_homo))*(y[39]);
 	 ydot[40] = (-(2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[0])*k_phos)+1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos))*(y[40])+(-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos))*(y[42])+(2.00e+00*(1.00e+00*k_exp_homo)*(nuc/cyt))*(y[45])+(1.00e+00*k_exp_hetero*(nuc/cyt))*(y[46]);
 	 ydot[41] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[0])*k_phos)*(y[40])+(-(1.00e+00*k_imp_homo))*(y[41])-y[1];
 	 ydot[42] = (-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos))*(y[40])+(-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos+2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[2])*k_phos)))*(y[42])+(1.00e+00*k_exp_hetero*(nuc/cyt))*(y[46])+(2.00e+00*(1.00e+00*k_exp_homo)*(nuc/cyt))*(y[47]);
 	 ydot[43] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos)*(y[40])+(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos)*(y[42])+(-(1.00e+00*k_imp_hetero))*(y[43]);
 	 ydot[44] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[2])*k_phos)*(y[42])+(-(1.00e+00*k_imp_homo))*(y[44])-y[4];
 	 ydot[45] = (1.00e+00*k_imp_homo*(cyt/nuc))*(y[41])+(-(1.00e+00*k_exp_homo))*(y[45])+y[1]*(cyt/nuc);
 	 ydot[46] = (1.00e+00*k_imp_hetero*(cyt/nuc))*(y[43])+(-(1.00e+00*k_exp_hetero))*(y[46]);
 	 ydot[47] = (1.00e+00*k_imp_homo*(cyt/nuc))*(y[44])+(-(1.00e+00*k_exp_homo))*(y[47])+y[4]*(cyt/nuc);
 	 ydot[48] = (-(2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[0])*k_phos)+1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos))*(y[48])+(-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos))*(y[50])+(2.00e+00*(1.00e+00*k_exp_homo)*(nuc/cyt))*(y[53])+(1.00e+00*k_exp_hetero*(nuc/cyt))*(y[54]);
 	 ydot[49] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[0])*k_phos)*(y[48])+(-(1.00e+00*k_imp_homo))*(y[49]);
 	 ydot[50] = (-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos))*(y[48])+(-(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos+2.00e+00*(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[2])*k_phos)))*(y[50])+(1.00e+00*k_exp_hetero*(nuc/cyt))*(y[54])+(2.00e+00*(1.00e+00*k_exp_homo)*(nuc/cyt))*(y[55]);
 	 ydot[51] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[2]*k_phos)*(y[48])+(1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*y[0]*k_phos)*(y[50])+(-(1.00e+00*k_imp_hetero))*(y[51])-y[3];
 	 ydot[52] = (1.00e+00*(1.25e-07*exp(-1.00e+00*Epo_degradation_BaF3*time))*(2.00e+00*y[2])*k_phos)*(y[50])+(-(1.00e+00*k_imp_homo))*(y[52]);
 	 ydot[53] = (1.00e+00*k_imp_homo*(cyt/nuc))*(y[49])+(-(1.00e+00*k_exp_homo))*(y[53]);
 	 ydot[54] = (1.00e+00*k_imp_hetero*(cyt/nuc))*(y[51])+(-(1.00e+00*k_exp_hetero))*(y[54])+y[3]*(cyt/nuc);
 	 ydot[55] = (1.00e+00*k_imp_homo*(cyt/nuc))*(y[52])+(-(1.00e+00*k_exp_homo))*(y[55]);

}

